export const REPOSITORIES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  SUPER_USER_REPOSITORY: 'SUPER_USER_REPOSITORY',
  LOGIN_TOKEN_REPOSITORY: 'LOGIN_TOKEN_REPOSITORY',
  COMPANY_REPOSITORY: 'COMPANY_REPOSITORY',
  COMPANY_USERS_REPOSITORY: 'COMPANY_USERS_REPOSITORY',
  USER_LOCATION_REPOSITORY: 'USER_LOCATION_REPOSITORY',
};